FROM python:3.7.12-slim-bullseye
MAINTAINER junseok.park@childrens.harvard.edu

ARG SYNAPSE_ID
ARG SYNAPSE_PASSWORD

ENV SYNAPSE_ID=${SYNAPSE_ID}
ENV SYNAPSE_PASSWORD=${SYNAPSE_PASSWORD}

## Install synapseClient
RUN pip install synapseclient




