apiVersion: apps/v1
kind: Deployment
metadata:
  name: fatima-test
  generation: 1
  labels:
    app: fatima-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fatima-test
  template:
    metadata:
      labels:
        app: fatima-test
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: c-fatima-test
          image: gcr.io/aleelab-genomeflow/ad_transposon:1.0
          resources:
            limits:
              memory: "55.2Gi" #(27.2, 55.2)
              cpu: "7500m" #(7700, 15700m)
            requests:
              memory: "55Gi" #27
              cpu: "7400m" #(7600, 15600m, 55)
          command: ["/bin/bash"]
          stdin: true
          tty: true
          env:
            - name: PROJECT_NAME
              value: "fatima-test-jobs"
            - name: TOTAL_TASK_COUNTS
              value: "1000"
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: "none"
            - name: WORK_PATH
              value: /app/rtea
            - name: TEMP_PATH
              value: /app/rtea/output
            - name: MULTI_THREADS
              value: "8"
            - name: TARGET_FILE_EXT
              value: bam
            - name: REF_BUCKET
              value: ad_transposon
            - name: REF_PREFIX
              value: refs
            - name: REF_PATH
              value: /app/rtea/hg38
            - name: OUTPUT_BUCKET
              value: ad_transposon
            - name: DB_USER
              value: aleelab
            - name: DB_PASSWORD
              value: aleelabAprom3!
            - name: DB_HOST
              value: 34.73.61.94
            - name: DB_NAME
              value: logger_db
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/keys/google-key.json
      nodeSelector:
        cloud.google.com/gke-nodepool: adtransposon-mem