apiVersion: apps/v1
kind: Deployment
metadata:
  name: monocyte-transposon-bastion
  generation: 1
  labels:
    app: monocyte-transposon-bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monocyte-transposon-bastion
  template:
    metadata:
      labels:
        app: monocyte-transposon-bastion
    spec:
#      volumes:
#        - name: pv-storage-worker
#          persistentVolumeClaim:
#            claimName: pv-claim-ad-worker
#            readOnly: true
        #- name: pv-nfs
        #  persistentVolumeClaim:
        #    claimName: fileserver-claim
        #    readOnly: false
      dnsPolicy: ClusterFirst
      containers:
        - name: c-monocyte-transposon-bastion
          image: gcr.io/aleelab-ten/monocyte-transposon-bastion:0.1
          command: ["/bin/bash"]
          stdin: true
          tty: true
#          volumeMounts:
#            - mountPath: /worker
#              name: pv-storage-worker
#              readOnly: true
            #- mountPath: /nfs-data
            #  name: pv-nfs
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool