apiVersion: batch/v1
kind: Job
metadata:
  name: job-ad-transposon-new-51
spec:
  backoffLimit: 900
#  completions: 546 # Current 2 executed
  completions: 1
  parallelism: 1 # to g6
  template:
    metadata:
      name: job-ad-transposon-new-51
    spec:
      terminationGracePeriodSeconds: 0
      dnsPolicy: ClusterFirst
      containers:
      - name: c-job-ad-transposon-new-51
        image: gcr.io/aleelab-genomeflow/ad_transposon:1.0
        resources:
          limits:
            memory: "55.2Gi" #(11.6Gi, 27.2, 55.2)
            cpu: "7500m" #(3700,7700, 15700m)
          requests:
            memory: "55Gi" #11.4Gi, 27
            cpu: "7400m" #(3600,7600, 15600m, 55)
        stdin: true
        tty: true
        env:
          - name: PROJECT_NAME
            value: "ad_transposon_rosemap_dlpfc"
          - name: TOTAL_TASK_COUNTS
            value: "252"
          - name: BROKER_URL
            value: amqp://guest:guest@rabbitmq-service:5672
          - name: QUEUE
            value: "list_new_dlpfc_tagged"
          - name: WORK_PATH
            value: /app/rtea
          - name: TEMP_PATH
            value: /app/rtea/output
          - name: MULTI_THREADS
            value: "8"
          - name: TARGET_FILE_EXT
            value: bam
          - name: REF_BUCKET
            value: ad_transposon
          - name: REF_PREFIX
            value: refs
          - name: REF_PATH
            value: /app/rtea/hg38
          - name: OUTPUT_BUCKET
            value: ad_transposon
          - name: DB_USER
            value: aleelab
          - name: DB_PASSWORD
            value: aleelabAprom3!
          - name: DB_HOST
            value: 34.73.61.94
          - name: DB_NAME
            value: logger_db
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /root/keys/google-key.json
      restartPolicy: Never
      #restartPolicy: OnFailure
      nodeSelector:
        cloud.google.com/gke-nodepool: adtransposon-nmem
