apiVersion: apps/v1
kind: Deployment
metadata:
  name: monocyte-test
  generation: 1
  labels:
    app: monocyte-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monocyte-test
  template:
    metadata:
      labels:
        app: monocyte-test
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: c-monocyte-test
          image: gcr.io/aleelab-ten/rtea-tcga:2.1.17
          resources:
            limits:
              memory: "27.2Gi" #(27.2, 55.2)
              cpu: "7500m" #(7700, 15700m)
            requests:
              memory: "27Gi" #27, 55
              cpu: "7400m" #(7600, 15600m, 55)
          command: ["/bin/bash"]
          stdin: true
          tty: true
          env:
            - name: PROJECT_NAME
              value: "aleelab-ten"
            - name: TOTAL_TASK_COUNTS
              value: "100"
            - name: BROKER_URL
              value: "amqp://guest:guest@rabbitmq-service:5672"
            - name: QUEUE
              value: "Random"
            - name: WORK_PATH
              value: "/app/rtea"
            - name: TEMP_PATH
              value: "/app/rtea/output"
            - name: MULTI_THREADS
              value: "8"
            - name: TARGET_FILE_EXT
              value: "fastq.gz"
            - name: REF_BUCKET
              value: "aleelab-ten-tcga-ref"
            - name: REF_PREFIX
              value: "grch38_snp_tran"
            - name: REF_PATH
              value: "/app/rtea/hg38"
            - name: OUTPUT_BUCKET
              value: "aleelab-monocyte-results"
            - name: DB_USER
              value: "aleelab"
            - name: DB_PASSWORD
              value: "aleelabAprom3!"
            - name: DB_HOST
              value: "34.73.61.94"
            - name: DB_NAME
              value: "logger_db"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/rtea/aleelab-ten-key.json"
            - name: CREDENTIAL_FILE_NAME
              value: "/app/rtea/token.ngc"
      #restartPolicy: Never
      #restartPolicy: OnFailure
      nodeSelector:
        cloud.google.com/gke-nodepool: compute-test